### ISSUE TITLE
Dúvidas De Funcionamento 2018

### ISSUE THREAD

**Issue by PauloBoaventura** [tiaguinho/correios#1]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

**Comment by tiaguinho** [comment]
Fala @PauloBoaventura tudo bem?

Acho que ouve alguma confusão por sua parte.
Esse pacote não funciona em nenhuma versão de PHP pois foi escrito para ser usado em Go.

Sobre ele funcionar, rodei um teste unitário hoje, e o único problema que tive foi o prazo de entrega do cep que uso no teste mudou de 4 para 5 dias.

**Comment by PauloBoaventura** [comment]
Olá @tiaguinho 
Bom o que preciso nesta implementação é que funcione com a plataforma magento 1.9 ou 2.1.
E que consiga colocar os valores descritivos no fechamento do produto. 

Se souber algo, me informe!
Abs!

**Comment by tiaguinho** [comment]
@PauloBoaventura Essa implementação não foi feita para PHP, logo não vai funcionar no magente.
A linguagem que utilizei nessa implementação chama-se [GO](https://golang.org/).

De qualquer forma, respondendo a sua dúvida, essa implementação funciona em 2018, assim como podemos ver nos testes unitários.
